### ISSUE TITLE
2 accounts 2 bots

### ISSUE THREAD

**Issue by JLN187** [TwitchIO/TwitchIO#102]
So Im trying to run 2 different bots each one running on their own accounts - starting both goes fine but the output is always happening on one of the bots no matter what.

**Comment by IAmTomahawkx** [comment]
This is not an issue with twitchio.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join the official [pythonista](https://discord.gg/RAKc3HF)
in addition you havent given any info whatsoever

**Comment by JLN187** [comment]
Mhhh thought I would be at the right place here - a moderator of the twitch dev forum told me to report it here :/
