### ISSUE TITLE
/me command as a message comes in as ACTION message

### ISSUE THREAD

**Issue by semaj4712** [TwitchIO/TwitchIO#108]
**Describe the bug**
When someone in chat types /me command it wraps the message in an unknown character and adds ACTION at the start, is there a way to parse this differently so that it comes in as expected /me message

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
1.1.0

**To Reproduce**
 @betbot.event
    async def event_message(ctx):
        print(ctx.content)

and type /me message in twitch

**Expected behaviour**
I would expect it to return /me message

**(please complete the following information):**
 - OS: Windows

**Comment by LeotomasMC** [comment]
this is simply how twitch handles /me internally, and is how the irc client knows to format the message in a special way

**Comment by semaj4712** [comment]
Ok thanks for the info, I will see if I can parse this information
