### ISSUE TITLE
Feature request: Stream title changing

### ISSUE THREAD

**Issue by Davidy22** [TwitchIO/TwitchIO#110]
A builtin for altering stream title, maybe categories and game, would be nice.

**Comment by Bluscream** [comment]
https://twitchio.dev/en/latest/reference.html#twitchio.Stream.title

Can this be changed?

**Comment by chillymosh** [comment]
Yes, I recommend joining the discord or opening / checking the discussion / checking the docs, as this isn't an issue.

**Comment by Bluscream** [comment]
I checked the docs but can't find anything regarding changing the stream info

**Comment by chillymosh** [comment]
If you check the Discussions, as suggested, you'd see this question was already asked and answered.
Please stop replying in a closed issue, that is not an issue.
https://github.com/TwitchIO/TwitchIO/discussions/301
