### ISSUE TITLE
Add Remove Channel For Bot

### ISSUE THREAD

**Issue by i007c** [TwitchIO/TwitchIO#115]
pls add function remove channel for bot 
i can't leave from channel

**Comment by Skaft** [comment]
Are you looking for [bot.part_channels](https://twitchio.readthedocs.io/en/rewrite/twitchio.commands.html#twitchio.ext.commands.bot.Bot.part_channels), or did you mean something else?

**Comment by i007c** [comment]
Oh sorry after I started reading Twitch docs, and i learned but I forgot to close this issue
