### ISSUE TITLE
subscribers / subscriberoff commands

### ISSUE THREAD

**Issue by 1271** [TwitchIO/TwitchIO#117]
Hi. This command cannot be called directly and twitchio does not have a command to send a command through the method. How?

Thank you

**Comment by IAmTomahawkx** [comment]
you've given no useful info in your issue. please describe the problem in detail, and give code examples. Following the issue template is helpful

**Comment by 1271** [comment]
Forget it, problem solved

**Comment by 1271** [comment]
P.S. you disallow sending the `/subscribers` and `/subscribersoff` command directly, but you don't have a method to call it. That was the problem.
