### ISSUE TITLE
Messages from users with an active Twitch Prediction throw exceptions and aren't handled

### ISSUE THREAD

**Issue by dewiniaid** [TwitchIO/TwitchIO#120]
**Describe the bug**
Twitch has a new "Predictions" feature, which more-or-less allows users to gamble channel points towards one of two possible outcomes with the streamer then determining what the outcome is.  Users with an active prediction get a new temporary badge (e.g. "blue-1") identifying their prediction.

Messages sent by these users cause the following exception (or similar):
```
Traceback (most recent call last):
  File "D:\git\twitchbot\venv\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "D:\git\twitchbot\venv\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "D:\git\twitchbot\venv\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
```

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Version: 1.1.0

**To Reproduce**
As a streamer or moderator: Open a create prediction in Twitch with `/prediction`
Then, as a non-moderator (Moderators and non-moderators cannot make predictions): Use channel points to make a prediction, then send a message.

**Expected behaviour**
Messages should be parsed and handled like all other messages

**(please complete the following information):**
- Python 3.8.5
- Windows 10

**Comment by IAmTomahawkx** [comment]
This has been fixed with V1.2.0
