### ISSUE TITLE
Proper capitalization on usernames

### ISSUE THREAD

**Issue by BLANK-TH** [TwitchIO/TwitchIO#126]
Currently the usernames from user.name are all lowercase, is there a way to make it the same capitalization as on Twitch?

**Comment by zaxutic** [comment]
This is the intended behaviour, usernames on Twitch are all lowercase. What you're looking for is `User.display_name`, which is what Twitch uses for capitalisation, though this appears to be undocumented in TwitchIO.

**Comment by TheodoreHua** [comment]
Ah I see, my mistake. I didn't see it on the documentation (or at a quick glance to the code) so it thought it didn't exist

**Comment by BLANK-TH** [comment]
Ah I see, I didn't see that on a quick glance to the code nor in the help docs so I thought it didn't exist. Thanks

(Also it seems that this is very similar to the discord.py module)
