### ISSUE TITLE
bot.unload_module doesn't work

### ISSUE THREAD

**Issue by GMJal** [TwitchIO/TwitchIO#128]
**Describe the bug**

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
?

**To Reproduce**
Steps to reproduce the behaviour:
bot.unload_module("Cogs.lsn")

**Expected behaviour**
want to unload the cog lsn.

**Screenshots**
`Ignoring exception in command: module 'Cogs.lsn' has no attribute 'breakdown':
Traceback (most recent call last):
  File "C:\Users\gmjal\.virtualenvs\TBot-G7gHstML\lib\site-packages\twitchio\ext\commands\bot.py", line 526, in handle_commands
    await ctx.command._callback(ctx, *ctx.args, **ctx.kwargs)
  File "F:\TBot\bot.py", line 31, in reload_commands
    bot.unload_module(f"Cogs.{filename[:-3]}")
  File "C:\Users\gmjal\.virtualenvs\TBot-G7gHstML\lib\site-packages\twitchio\ext\commands\bot.py", line 216, in unload_module
    module.breakdown(self)
AttributeError: module 'Cogs.lsn' has no attribute 'breakdown'`

**(please complete the following information):**
 - OS: Windows 10 20H2

**Additional context**
Nothing

**Comment by IAmTomahawkx** [comment]
Please add a function called breakdown to your module. It should remove any cogs that belong to the module

**Comment by IAmTomahawkx** [comment]
Additionally, this is not actually an issue with twitchio, please join the discord server for help with the library, as the [readme recommends](https://github.com/TwitchIO/TwitchIO#support)
