### ISSUE TITLE
on_follow_event / on_subscription_event / ...

### ISSUE THREAD

**Issue by kkrypt0nn** [TwitchIO/TwitchIO#132]
Adding events for when users follow,  subscribe, give bits, ... on a channel would make many things much more easier.

In the meantime, I was wondering how the Webhook works? Like how can you subscribe to a Webhook like `Webhook.UserFollows` and then gather the name of the user who followed (or subscribed) everytime someone follows the channel.

**Comment by IAmTomahawkx** [comment]
These are available through PubSub
