### ISSUE TITLE
[ Feature request ] Get mod who banned

### ISSUE THREAD

**Issue by Dschogo** [TwitchIO/TwitchIO#133]
Add the mod (mod id) in for example "event_raw_data".

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
`pip show twitchio` command somehow doesnt work 
its version 1.1.0 installed through pip

**Comment by IAmTomahawkx** [comment]
This is on the project board for 2.0 ( #123 )
