### ISSUE TITLE
get_followers() returns Unauthorized: You're not authorized to use this route regardless of twitch scopes

### ISSUE THREAD

**Issue by semaj4712** [TwitchIO/TwitchIO#135]
**Describe the bug**
get_followers() returns Unauthorized: You're not authorized to use this route regardless of twitch scopes

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
1.1.0

**To Reproduce**
try and run get_followers() on either the initial_channel userid or the authorized bots userid

**Expected behaviour**
It should send me back a list of followers

**(please complete the following information):**
 - OS: Windows

**Comment by IAmTomahawkx** [comment]
update your twitchio

**Comment by semaj4712** [comment]
Thanks but 1.2.1 did not fix it

**Comment by IAmTomahawkx** [comment]
join the pythonista [discord](https://discord.gg/RAKc3HF) for support in that case

**Comment by semaj4712** [comment]
Thanks I will

**Comment by phantomeniasll** [comment]
Where did you get your Token. Are you sure it is a User and Bearer Token? Try using https://twitchtokengenerator.com/ to generate it, helped me.
If you want an example look in https://dev.twitch.tv/docs/api/reference#get-users-follows .
