### ISSUE TITLE
2 Fixes for Problems when refunding custom rewards and getting reward redemptions.

### ISSUE THREAD

**Issue by phantomeniasll** [TwitchIO/TwitchIO#136]
**Describe the bug**
1.Refunding a custom reward doesn't works with .refund() .
2.get_reward_redemptions() always throws an error.

**Are you using TwitchIO within a Discord Bot?**
Yes

**What commit of TwitchIO are you using?**
1.2.0

**How to fix these Bugs:**
1. in dataclasses.py in line 647/648
`data = await self._http.update_reward_redemption_status(token, self._broadcaster_id, self.id, reward_id,
                                                                    "CANCELLED")`
has to be 
`data = await self._http.update_reward_redemption_status(token, self._broadcaster_id, self.id, reward_id,
                                                                    False)`
and in http.py in line 416
` status = "FULFILLED" if status else "CANCELLED"`
has to be
` status = "FULFILLED" if status else "CANCELED"` because the Twitch API only wants 1 L

2. in http.py there is a / missing in line 412 
`return await self.request("GET", "channel_points/custom_rewards/redemptions", params=params, headers={"Authorization": f"Bearer {token}"}, limit=limit)`
has to be 
`return await self.request("GET", "/channel_points/custom_rewards/redemptions", params=params, headers={"Authorization": f"Bearer {token}"}, limit=limit)`

**(please complete the following information):**
 - OS: Windows 10

**Comment by IAmTomahawkx** [comment]
I couldn't actually test these as I'm not an affiliate, so thanks!
