### ISSUE TITLE
RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited

### ISSUE THREAD

**Issue by TECHNOFAB11** [TwitchIO/TwitchIO#137]
**Describe the bug**
The websocket.close() method has to be awaited, otherwise a RuntimeWarning is shown and the bot doesnt shutdown successfully.

**Are you using TwitchIO within a Discord Bot?**
No, technically parallel to one. Most important information is that its running inside of an `asyncio.Task`.

**What commit of TwitchIO are you using?**
Version 1.2.1

**To Reproduce**
Wrap the client.start() method in a task, then cancel the task later (as there is not logout or close method there is no other way than to just cancel it)

**Expected behaviour**
It shouldnt throw a RuntimeWarning

**my working Solution**
Changing this 
https://github.com/TwitchIO/TwitchIO/blob/cd6c97b8408772d0d5f14ce082ac25d8b9c4ec51/twitchio/ext/commands/bot.py#L330
to `await self._ws.teardown()`, this
https://github.com/TwitchIO/TwitchIO/blob/cd6c97b8408772d0d5f14ce082ac25d8b9c4ec51/twitchio/websocket.py#L625
to `async def` and
https://github.com/TwitchIO/TwitchIO/blob/cd6c97b8408772d0d5f14ce082ac25d8b9c4ec51/twitchio/websocket.py#L629
to `await self._websocket.close()`

Also the `run` method should just run the `start` method in the loop imo, otherwise you'd have to add another `loop.run_until_complete` for the teardown

**Comment by TECHNOFAB11** [comment]
Seems to be fixed in #93, but it hasnt been merged and is many months old.

**Comment by IAmTomahawkx** [comment]
Thanks, i hadn't seen that issue. I've reviewed it now
