### ISSUE TITLE
Bot connects to first letter of channel if 'initial_channels' is a string

### ISSUE THREAD

**Issue by Stevoisiak** [TwitchIO/TwitchIO#138]
**Describe the bug**
If a Bot is initialized by passing `initial_channels` as a string instead of a list, the Bot will treat the string as a list and attempt to connect to the first letter of the channel name.

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Version 1.2.1

**To Reproduce**
1. Create a file `bot.py` with the following code

```Python
import os
from twitchio.ext import commands
from dotenv import load_dotenv
load_dotenv() # load environment variables

class Bot(commands.Bot):
    async def event_ready(self):
        print("I am online")

bot = Bot(irc_token=os.environ['TMI_TOKEN'], client_id=os.environ['CLIENT_ID'], nick=os.environ['BOT_NICK'],
          prefix=os.environ['BOT_PREFIX'], initial_channels='example_channel')
bot.run()
```

2. Create a `.env` file with the required environment variables
3. Run `bot.py`

**Expected behaviour**
Either the bot connects to the given channel name, or a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) is raised indicating that `initial_channels` expects a list or tuple.

**Additional context**
OS: Windows 10 Pro (1909)

Traceback
```
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<WebsocketConnection.auth_seq() done, defined at C:\Users\stevo\Documents\GitHub\twitch-bot\env\lib\site-packages\twitchio\websocket.py:200> exception=TimeoutError('Request to join the "e" channel has timed out. Make sure the channel exists.')>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stevo\Documents\GitHub\twitch-bot\env\lib\site-packages\twitchio\websocket.py", line 280, in _join_channel
    await asyncio.wait_for(fut, timeout=10)
  File "C:\Python39\lib\asyncio\tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stevo\Documents\GitHub\twitch-bot\env\lib\site-packages\twitchio\websocket.py", line 228, in auth_seq
    await self.join_channels(*channels)
  File "C:\Users\stevo\Documents\GitHub\twitch-bot\env\lib\site-packages\twitchio\websocket.py", line 271, in join_channels
    await asyncio.gather(*[self._join_channel(x) for x in channels])
  File "C:\Users\stevo\Documents\GitHub\twitch-bot\env\lib\site-packages\twitchio\websocket.py", line 284, in _join_channel
    raise asyncio.TimeoutError(
asyncio.exceptions.TimeoutError: Request to join the "e" channel has timed out. Make sure the channel exists.
```

**Comment by IAmTomahawkx** [comment]
Initial channels should be a list of strings. The library is not, nor should it be, responsible for bad arguments, when the arguments are documented

**Comment by Stevoisiak** [comment]
> Initial channels should be a list of strings. The library is not, nor should it be, responsible for bad arguments, when the arguments are documented

I think raising a TypeError before attempting a connection would make it easier for users to troubleshoot the issue. The documentation is appreciated however, as reviewing it helped figure out what was going on.

**Comment by wantyapps** [comment]
Any updates on this? It still doesn't work...

**Comment by wantyapps** [comment]
Am I supposed to use list (str) type?

**Comment by wantyapps** [comment]
well yeah

**Comment by wantyapps** [comment]
a list of strs

**Comment by wantyapps** [comment]
But it doesn't work

**Comment by IAmTomahawkx** [comment]
As a final response to this issue, it's not up to the library to validate every input that the user gives. There has to be some level of competence from the user in the form of reading the documentation (or even if not, the fact that it's pluralized is a bit of an indicator). If the anyone finds it *that* important that the library validates this type, open a pr and then we can talk

**Comment by wantyapps** [comment]
Sorry, it was probably somehow my mistake. I will rewrite the bot. Thanks for the help

**Comment by 1987Krang1987** [comment]
Hi all, in this moment I have a similar problem:

The channel "XXXX" was unable to be joined. Check the channel is valid.
Task exception was never retrieved
future: <Task finished name='Task-135' coro=<WSConnection._join_future_handle() done, defined at E:\Lib\site-packages\twitchio\websocket.py:325> exception=KeyError('krangcl')>
Traceback (most recent call last):
  File "E:\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:


Translate to English: "I created a bot for Twitch that starts perfectly and can run for an hour with all its commands. The problem is that after a while, it loses connection to my channel. I don't know the reason or how to solve it, and I don't have any connection issues either."

My Code:

client_id = 'client_id '
canal_id = "canal_id "
token = 'token'

Yuumia = commands.Bot(
    token = token,
    client_id = client_id,
    nikc = 'BotYuumIA',
    prefix = '!',
    initial_channels = [canal_id]
)

Thank you for any help.

**Comment by IAmTomahawkx** [comment]
Please open a [discussion](https://github.com/TwitchIO/TwitchIO/discussions) for assistance, thanks

**Comment by 1987Krang1987** [comment]
i gona do it, thk
