### ISSUE TITLE
Calling get_stream() from event_ready() raises an authorization error

### ISSUE THREAD

**Issue by Stevoisiak** [TwitchIO/TwitchIO#139]
**Describe the bug**
Calling the `get_stream()` method from `event_ready()` raises an error stating "You're not authorized to use this route". This issue does not occur if `get_stream()` is called from other methods such as `event_message()`.

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
1.2.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a basic TwitchIO bot.
2. Attempt to call `get_stream()` from `event_ready()`

```Python
import os
from twitchio.ext import commands
from dotenv import load_dotenv
load_dotenv() # load environment variables from .env

class Bot(commands.Bot):
    def __init__(self):
        super().__init__(
            irc_token=os.environ['TMI_TOKEN'],
            client_id=os.environ['CLIENT_ID'],
            nick=os.environ['BOT_NICK'],
            prefix=os.environ['BOT_PREFIX'],
            initial_channels=[os.environ['CHANNEL']]
        )

    async def event_ready(self):
        'Called once when the bot goes online.'
        # Unauthorized exception when retrieving stream information
        stream_info = await self.get_stream(os.environ['CHANNEL'])

if __name__ == "__main__":
    bot = Bot()
    bot.run()
```

**Expected behaviour**
The `get_stream()` method returns information about the stream.

**Additional context**
OS: Windows 10 (1909)
Use case: Checking if a streamer is online when the bot first connects.

Exception
```
Message=You're not authorized to use this route.
Source=C:\Users\stevo\Documents\GitHub\Flock-Family\scrap2.py
StackTrace:
File "C:\Users\stevo\Documents\GitHub\Flock-Family\scrap2.py", line 19, in event_ready
  stream_info = await self.get_stream(os.environ['CHANNEL'])
File "C:\Users\stevo\Documents\GitHub\Flock-Family\scrap2.py", line 23, in <module>
  bot.run()
```

**Comment by Stevoisiak** [comment]
Figured out the authorization error can be avoided by providing a client_secret.
```Python
import os
from twitchio.ext import commands
from dotenv import load_dotenv
load_dotenv() # load environment variables from .env

class Bot(commands.Bot):
    def __init__(self):
        super().__init__(
            irc_token=os.environ['TMI_TOKEN'],
            client_id=os.environ['CLIENT_ID'],
            client_secret=os.environ['CLIENT_SECRET'],
            nick=os.environ['BOT_NICK'],
            prefix=os.environ['BOT_PREFIX'],
            initial_channels=[os.environ['CHANNEL']]
        )

    async def event_ready(self):
        'Called once when the bot goes online.'
        stream_info = await self.get_stream(os.environ['CHANNEL'])

if __name__ == "__main__":
    bot = Bot()
    bot.run()
```

**Comment by IAmTomahawkx** [comment]
This is not a bug, you must pass the `api_token` value to the constructor, or the `client_secret` value. sorry for the slow response

**Comment by Stevoisiak** [comment]
> This is not a bug, you must pass the `api_token` value to the constructor, or the `client_secret` value. sorry for the slow response

Why do calls to `get_stream()` work outside of `event_ready()` without passing `api_token` or `client_secret`?

**Comment by IAmTomahawkx** [comment]
Hold on. I read this as get_user, my mistake. This is most likely a race condition
