### ISSUE TITLE
Confusing checks in HTTPSession

### ISSUE THREAD

**Issue by Commaster** [TwitchIO/TwitchIO#140]
If we take a look at
https://github.com/TwitchIO/TwitchIO/blob/d1fe838d25b050d0265e5d9a75b09fad7f15d6a5/twitchio/http.py#L52
it says "or", but
https://github.com/TwitchIO/TwitchIO/blob/d1fe838d25b050d0265e5d9a75b09fad7f15d6a5/twitchio/http.py#L51
checks for "and". Which one is it?

Also we already checked for "not client_id" in
https://github.com/TwitchIO/TwitchIO/blob/d1fe838d25b050d0265e5d9a75b09fad7f15d6a5/twitchio/http.py#L48
so the second part of the aforementioned check will unnecessarily duplicate the warning.

Please clear up this confusion,
Thank you!

**Comment by IAmTomahawkx** [comment]
Honestly the http stuff is a mess not worth fixing. Twitchio 2 is almost ready for release, so fixing this now isn't really a priority

**Comment by Commaster** [comment]
Thank you. I will wait for the PyPi update!
