### ISSUE TITLE
Feature Request: Be able to get the ctx.message.clean_content, ie, the content of the message after the command, instead of having to split by the command name each time

### ISSUE THREAD

**Issue by BairdMcI** [TwitchIO/TwitchIO#141]
Having an automatic `clean_content` parameter which gives this, for example by calling
`clean_content = ctx.message.content.split(ctx.command.name)[1].strip()` would be really useful

**Comment by IAmTomahawkx** [comment]
Added to the 2.0 project board

**Comment by BairdMcI** [comment]
> > would be really useful
> 
> Can you help us understand why it would be useful? What is your use case?

Basically, it would be useful so that when a user calls a command with an argument after the command name, its easier to process.
Eg `!hello scragly and Luma` just gets and returns "scragly and Luma", so is easier for the bot to parse the inputs  and also works with case insensitive commands, which i realise my initial suggestion of how to implement doesn't allow. There may already be a good way to do this, in which case I apologise, I've not found it yet.

**Comment by scragly** [comment]
Hey, sorry for the slow reply. I meant to do it on the day, got distracted, did a bunch of stuff and then didn't remember to come back.

Yeah what you want can be done with twitchios command arguments:
```py
@bot.command(name='hello', aliases=['t'])
async def hello_command(ctx, *, message):
    await ctx.send(message)
```
```
!hello whatever you want here
```
will result in
```
whatever you want here
```

**Comment by scragly** [comment]
As there seems to be a suitable feature that exists for your use case, I'll close this request for now.
