### ISSUE TITLE
Trying to Use Client.get_users Results in an Error of TypeError

### ISSUE THREAD

**Issue by giladsher** [TwitchIO/TwitchIO#144]
**Describe the bug**
When trying to use the `Client.get_users` method, the code results in an error of `exception=TypeError('__new__() takes 10 positional arguments but 11 were given',)`

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Name: twitchio
Version: 1.2.1
Summary: A Python IRC and API wrapper for Twitch.
Home-page: https://github.com/TwitchIO/TwitchIO
Author: TwitchIO
Author-email: UNKNOWN
License: MIT
Location: c:\users\tripl\appdata\local\programs\python\python36\lib\site-packages
Requires: aiohttp, websockets, async-timeout
Required-by:

**To Reproduce**

1. Have a known user or users ID list (I used both a list and a single name which I know exists).
2. Instantiate a new `Client`.
3. Try to user `Client.get_users(user)` (or spread the users list)
4. See that you get an error of `exception=TypeError('__new__() takes 10 positional arguments but 11 were given',)`

**Expected behaviour**
`Client.get_users` works as expected and brings back a list of users.

**Screenshots**

![image](https://user-images.githubusercontent.com/39515060/109356796-e4d5c680-7889-11eb-94d4-8fe467e172ac.png)
![image](https://user-images.githubusercontent.com/39515060/109356843-f6b76980-7889-11eb-9eeb-bb585ce96a4a.png)

**(please complete the following information):**
 - OS: Windows

**Additional context**
I also noticed that the `profile_image_url` and `offline_image_url` that are getting from the API are not named correctly in the source code. 
![image](https://user-images.githubusercontent.com/39515060/109356981-223a5400-788a-11eb-8914-d64020d4576c.png)

**Comment by IAmTomahawkx** [comment]
this seems to be caused by the `email` value being passed if youve been granted that scope

**Comment by zoominGiladSher** [comment]
Thank you for the quick investigation and solution! 😊
