### ISSUE TITLE
Authentication error not detected

### ISSUE THREAD

**Issue by bestdani** [TwitchIO/TwitchIO#145]
**Describe the bug**
Authentication error is not detected

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
latest pypi package but should also be present in 2.0 from comparing the affected code

**To Reproduce**
Use some wrong oauth key on purpose

**Expected behaviour**
AuthenticationError should be raised instead of constantly reconnecting because the websocket gets closed.

**Additional context**
I worked around the problem by hotfixing it on my system.

Instead of checking for equality of the auth error string with data I just checked if data contains the string since the reason seems to be that twitch started(?) to send caps answers and authentication errors in a single data event.

line 382 in websocket.py `'elif :tmi.twitch.tv NOTICE * :Login authentication failed' in data or ...`

So there might be room for cleaner solutions like splitting the messages (divided by \r\n).`

Example data block that was not be able to successfully detected as some authentication error without my hotfix:
`b':tmi.twitch.tv NOTICE * :Login authentication failed\r\n:tmi.twitch.tv CAP * ACK :twitch.tv/commands\r\n:tmi.twitch.tv CAP * ACK :twitch.tv/tags\r\n'`

**Comment by EvieePy** [comment]
This should not be a problem in 2.0 as 2.0 validates the token against twitches validate endpoint. But I will look at a hotfix for version 1.x

**Comment by bestdani** [comment]
> This should not be a problem in 2.0 as 2.0 validates the token against twitches validate endpoint. But I will look at a hotfix for version 1.x

I think one should not rely on that a validated auth key guarantees a successful IRC login in every circumstance.

**Comment by EvieePy** [comment]
A valid OAuth token should not rerturn an Authentication Failed. It doesn't necessarily mean that it will logon to IRC in every case, but it shouldn't be an authentication problem (Unless someone can clear that up with certainty).

**Comment by EvieePy** [comment]
So yes I agree something needs to be done in the case the token is not able to login e.g a Login unsuccessful NOTICE, but in the case of Authentication, that should never be a problem.

**Comment by EvieePy** [comment]
Honestly though that's just Twitch semantics. A token without chat_login scope should still return an authentication error over IRC.

**Comment by EvieePy** [comment]
2.0 should now handle all cases of incorrect tokens being passed when attempting to connect to IRC, including those that do not have `chat_login` scope. cabd493f07a05261306297ede2e7135be23333b2
