### ISSUE TITLE
(2.x) Whisper

### ISSUE THREAD

**Issue by rn4n** [TwitchIO/TwitchIO#146]
Hello! 🙋🏻‍♂️

Would it be possible to provide a way to send a whisper message for an user? Something like:
```py
async def reply_as_whisper(ctx):
   await ctx.whisper("username", "The message content.")
```
I came from [tmi](https://github.com/tmijs/tmi.js) ([`whisper` implementation](https://github.com/tmijs/tmi.js/blob/4bb66c433b8ae28326b4cd8567357e6ea729e91a/lib/commands.js#L535-L571)) and this is a feature that I miss. I don't know if this information is relevant but, to use the whisper feature, it is first necessary to verify the bot through this [Twitch form](https://dev.twitch.tv/limit-increase).

Thanks for this library and for all abstraction provided.

**Comment by nxtlo** [comment]
`ctx.whisper` should be `await` not `async`

**Comment by rn4n** [comment]
@nxtlo fixed, thanks.

**Comment by IAmTomahawkx** [comment]
Hi there, Twitchio V1 is currently in critical-fix-only mode right now, as we put our efforts towards wrapping up Twitchio 2. If Twitchio2 does not already implement your issue, please change your issue title to be prefixed with `(2.x)`

**Comment by EvieePy** [comment]
Sorry it's taken some time to get to this. We are discussing how we would like to implement such a feature.

**Comment by chillymosh** [comment]
Twitch now block whispers unless you are verified and whitelisted bot, and even then they do not guarantee it will be successful.

**Comment by rn4n** [comment]
In fact this "problem" of preventing the use of whispers has always existed, but Twitch doesn't make it clear, usually just find out about the need to verify a bot when started to [searching on the developer forums](https://discuss.dev.twitch.tv/t/whispers-do-not-appear-to-the-viewer/24003/2).

Still, I think the library can implement this feature and make it available for use, just like tmi.js did. That issue about instability is already mentioned by some developers and normal users in their [user voice](https://twitch.uservoice.com/search?filter=ideas&query=whisper). Let Twitch working on it. 😅

Once the feature is implemented, I can include a note in the TwitchIO documentation about the need for bot verification, as well as referral links to do this. If Twitch itself doesn't care to make it clear, we can make it clear to the people who use the library.

**Comment by chillymosh** [comment]
The best resource for this issue is the official Twitch API Discord with the devs and they have always stated it's unreliable, even for verified bots.
