### ISSUE TITLE
The properties of User object are exchanged

### ISSUE THREAD

**Issue by rn4n** [TwitchIO/TwitchIO#147]
**Describe the bug**
The properties of  `User` object are exchanged.

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
```
Name: twitchio
Version: 1.2.2
Summary: A Python IRC and API wrapper for Twitch.
Home-page: https://github.com/TwitchIO/TwitchIO
Author: TwitchIO
Author-email: UNKNOWN
License: MIT
Location: ,venv\site-packages
Requires: aiohttp, async-timeout, websockets
Required-by:
```

**To Reproduce**
Just setup the client settings:

```py
from twitchio import Client

client = Client(
    client_id="the client id",
    client_secret="client secret",
)
```
And call `get_users` inside any async function:
```py
await client.get_users("gaules")
```

The return value is:
> [User(id='181077473', login='gaules', display_name='Gaules', type='', broadcaster_type='partner', description='Mais um guerreiro da Maior Tribo do Mundo! Atuei como jogador profissional de CS por quase uma década, fui o primeiro treinador a ser campeão do mundo em 2007 com o MIBR. Acertei um pouco, errei muito, ganhei bastante coisa e tbm perdi demais! Atualmente faço live todos 
os dias aqui na Twitch! ', profile_image=251644947, offline_image='2017-11-09T14:10:52.83257Z', view_count='https://static-cdn.jtvnw.net/jtv_user_pictures/5deb9374-f180-4ee0-8446-205cde623ec8-channel_offline_image-1920x1080.png', created_at='https://static-cdn.jtvnw.net/jtv_user_pictures/c495b77e-7f47-4bc5-a216-3045d7545796-profile_image-300x300.png', email=None)]

**Problems**:
- `profile_image`  contains the value of view count;
- `view_count` have the value of the offline image URL;
- `offline_image` contains the value of the created_at;
- `created_at` has the profile image URL.

---

 - OS: win10 64
 - Python 3.9.1

**Comment by sphaax** [comment]
'offline_image' field is also exchanged with the 'created_at' one ;)

**Comment by bpafoshizle** [comment]
Seeing the same: 

Version 1.2.1 returns:

`INFO:cogs.twitch:[User(id='15564828', login='nickmercs', display_name='NICKMERCS', type='', broadcaster_type='partner', description='Former MLG National Champion. A fellow gym rat, who streams mostly Competitive Shooters! Thank you all so much for your continued support. Follow the stream and my Twitter account to be notified when I will be going live - @Nickmercs ', profile_image='https://static-cdn.jtvnw.net/jtv_user_pictures/ff13760d-d795-49d9-8f3f-f05035930c81-profile_image-300x300.png', offline_image='https://static-cdn.jtvnw.net/jtv_user_pictures/de5ae820-2fe8-412d-9979-1e8777908d7e-channel_offline_image-1920x1080.png', view_count=164492687, created_at='2010-09-13T05:01:35.371022Z')]`

Version 1.2.2 returns:

`INFO:cogs.twitch:[User(id='15564828', login='nickmercs', display_name='NICKMERCS', type='', broadcaster_type='partner', description='Former MLG National Champion. A fellow gym rat, who streams mostly Competitive Shooters! Thank you all so much for your continued support. Follow the stream and my Twitter account to be notified when I will be going live - @Nickmercs ', profile_image=164492687, offline_image='2010-09-13T05:01:35.371022Z', view_count='https://static-cdn.jtvnw.net/jtv_user_pictures/de5ae820-2fe8-412d-9979-1e8777908d7e-channel_offline_image-1920x1080.png', created_at='https://static-cdn.jtvnw.net/jtv_user_pictures/ff13760d-d795-49d9-8f3f-f05035930c81-profile_image-300x300.png', email=None)]`
