### ISSUE TITLE
TwitchIO 2.x feature implementation: Add in event_raw_usernotice to deal with subs, resubs, raids etc

### ISSUE THREAD

**Issue by DeadM8** [TwitchIO/TwitchIO#148]

**Comment by charlesmadere** [comment]
Is there any update/information about this feature? [I used to use `event_raw_usernotice` within my bot](https://github.com/charlesmadere/CynanBot/blob/d9c2e34d7c9fe8d2e0bb58401fcfc810757d76dd/cynanBot.py#L244), but unfortunately, this method seems to be doing nothing with TwitchIO 2.
