### ISSUE TITLE
[Feature Request] Chat Replies

### ISSUE THREAD

**Issue by GavinEke** [TwitchIO/TwitchIO#163]
The chat replies feature has rolled out to all Twitch channels, would be nice to have it on the backlog (low priority) to send a message in chat as a reply to a thread.

More info: https://help.twitch.tv/s/article/chat-basics?language=en_US#replies

**Comment by IAmTomahawkx** [comment]
ctx.reply now exists as of bc65337ea2cbaefb0ce641a4acc9b51b548f9adc
