### ISSUE TITLE
2.0: Typo in BroadCasterTypeEnum breaks User objects

### ISSUE THREAD

**Issue by izzy** [TwitchIO/TwitchIO#165]
**Describe the bug**
Can't create user objects for users who are affiliates.

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
2.0.0b4

**To Reproduce**
use `ctx.author.user()` with any user that's an affiliate

**Expected behaviour**
User object is created

**Additional context**
https://github.com/TwitchIO/TwitchIO/blob/2.0/twitchio/enums.py#L40

`affilate = "affilate"`

should be 

`affiliate = "affiliate"`

**Comment by IAmTomahawkx** [comment]
fixed in bab3f6c
