### ISSUE TITLE
Twitchio 2.0 message.author is None on echo messages

### ISSUE THREAD

**Issue by Stashiocat** [TwitchIO/TwitchIO#168]
**Describe the bug**
When your bot sends a message from within event_message, event_message will get called with message.author being None.

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Version: 2.0.0b4

**To Reproduce**
Steps to reproduce the behaviour:
1. Send a message within event_message
2. See that the author field is None when it's called with the echo message

**Expected behaviour**
The author should be a valid object

**(please complete the following information):**
 - OS: Windows 10

**Comment by IAmTomahawkx** [comment]
This is intentional, please check Message.echo to verify that it is an echo message before checking message.author (if its an echo message, your bot sent it)
