### ISSUE TITLE
Incoming whisper results in NoneType error while handling commands 

### ISSUE THREAD

**Issue by markd2** [TwitchIO/TwitchIO#172]
**Describe the bug**
An incoming whisper received in `event_message` causes `handle_commands` to die with a `NoneType object has no attribte _ws` error

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
`pip show twitchio`

That didn't do anything for me (using pipenv).  This is in my pipfile lock

```
       "twitchio": {
            "hashes": [
                "sha256:3ebb03425bf486a0a3812608a073adc54bfa458032748c37be06a4da38390970",
                "sha256:cd7768c173ce4364dc262e1cdd0c4c4291d768fdf387b10b8921bd4d18a3b07b"
            ],
            "index": "pypi",
            "version": "==2.0.0b7"
        },
```

**To Reproduce**

* have this event_message:

```
    async def event_message(self, message):
        print(f"{message.author} / {message.author}: {message.content}")

        # prevent us responding to ourselves.
        if message.echo:
            return

        await self.handle_commands(message)

        await message.channel.send(f"splunge {message.content}")
```

* Run the bot.
* in the chat for the stage the bot is listening in, post a message to test the bot is working.  typing "borK" should result in a response of "splunge bork"
* in the chat, enter the command `/w botname hello` (or use other mechanisms 

**Expected behaviour**

The event_message method processes the event (in this case, sending back to the channel the "splunge bork" response

What actually happened is this:

```
pipenv run python bot.py
Loading .env environment variables...
Logged in as | borkbot_songbot
<PartialChatter name: borkwaremarkd, channel: <Channel name: borkwaremarkd>> / <PartialChatter name: borkwaremarkd, channel: <Channel name: borkwaremarkd>>: spoon
None / None: splunge spoon
<WhisperChatter name: borkwaremarkd> / <WhisperChatter name: borkwaremarkd>: hello
Traceback (most recent call last):
  File "/Users/markd/.local/share/virtualenvs/zandemonium-w44pKbCL/lib/python3.7/site-packages/twitchio/client.py", line 149, in wrapped
    await func(*args)
  File "bot.py", line 35, in event_message
    await self.handle_commands(message)
  File "/Users/markd/.local/share/virtualenvs/zandemonium-w44pKbCL/lib/python3.7/site-packages/twitchio/ext/commands/bot.py", line 253, in handle_commands
    context = await self.get_context(message)
  File "/Users/markd/.local/share/virtualenvs/zandemonium-w44pKbCL/lib/python3.7/site-packages/twitchio/ext/commands/bot.py", line 223, in get_context
    return cls(message=message, prefix=prefix, valid=False, bot=self)
  File "/Users/markd/.local/share/virtualenvs/zandemonium-w44pKbCL/lib/python3.7/site-packages/twitchio/ext/commands/core.py", line 388, in __init__
    self._ws = self.channel._ws
AttributeError: 'NoneType' object has no attribute '_ws'
```

In particular, when running `self.handle_commands` to process out `!` commands, it tries to access a `NoneType`

**(please complete the following information):**
 - OS: MacOS Catalina 10.15.6 (19G73)
 - Python 3.9.5

**Additional context**

This is my pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
twitchio = "*"

[dev-packages]

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

and I installed via `pipenv install twitchio --pre` to get v2.

In general, though, I have no idea what I'm doing.  I'm markd2#7307 in the Pythonista Dicord and originally posted this there: https://discord.com/channels/490948346773635102/491048464831086592/848718727032864799

Thanks!  Enjoying twitchio.  Making bots is fun :-)

**Comment by IAmTomahawkx** [comment]
Fixed, thanks
