### ISSUE TITLE
EventMessage message author is None when message is from the bot

### ISSUE THREAD

**Issue by SHA65536** [TwitchIO/TwitchIO#177]
**Describe the bug**
When listening to messages, messages that are sent by the bot will have the author attribute set to None

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
2.0.0b7

**To Reproduce**
1. Set up a simple twitcio bot that responds to a command.
2. Inside event_message print ctx.author
3. See that when the message from the bot is received, the author is set to none

**Expected behavior**
I expect the author attribute to contain information about the bot.

**(please complete the following information):**
 - OS: Windows/Linux

**Additional context**
This is not how it works in 1.2.3

**Comment by JMcB17** [comment]
This may be intentional

**Comment by IAmTomahawkx** [comment]
You are right, that's not how it works in v1.x. But this is intentional.
