### ISSUE TITLE
Way to get streamers language?

### ISSUE THREAD

**Issue by ardumdev** [TwitchIO/TwitchIO#182]
Hi. When I use the function search_channels, and loop trough the results I can't find any fields for language. Twitch api says it should contain broadcaster_language, but when I looked at the source code it's not implemented. I even tried to loop trough connected channels. Is there a way how to get streamers language?

**Comment by rn4n** [comment]
@ardumdev can you confirm that you can get the user's language in version 2.0.6?

```python
channels = await cli.search_channels("foobar")
print(channels[0].language)
```

**Comment by chillymosh** [comment]
Just an FYI you can also fetch_channel now which returns a single channel with the language attribute.

**Comment by chillymosh** [comment]
Language can be fetched using fetch_channels method
