### ISSUE TITLE
[2.x] ConnectionResetError: Cannot write to closing transport when subscribing to PubSub

### ISSUE THREAD

**Issue by iarspider** [TwitchIO/TwitchIO#201]
I'm trying to use two different accounts in my bot: one (arachnobot) for dealing with chat, another (iarspider - streamer account) to handle channel rewards. This was working fine in 1.x (I implemented the actual handing of PubSub events myself), but in 2.x it fails with ConnectionResetError.

Code: https://gist.github.com/iarspider/c9ad987b7e34baaa28fd92b2186d4568
Log: https://gist.github.com/iarspider/b6db3b806bc32ad494528ae3780d7035

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
master (https://github.com/TwitchIO/TwitchIO/commit/c57c35b5ebabaed6e703a9907a38757b6d94dc90)

**Comment by chillymosh** [comment]
This could be related to https://github.com/TwitchIO/TwitchIO/issues/188 not 100% on that though

**Comment by iarspider** [comment]
> This could be related to #188 not 100% on that though

Seems to be the case. Closing in favor of #188

**Comment by iarspider** [comment]
Just in case anyone else needs help, I have updated the code to contain a working example. I had to move `Client` out of `Bot` in order to subscribe to an event
