### ISSUE TITLE
Leave channel function?

### ISSUE THREAD

**Issue by mmattbtw** [TwitchIO/TwitchIO#206]
We already have `join_channels`, why not have `leave_channels`?

**Comment by ExperimentalCyborg** [comment]
I second this. I need people to be able to remove my bot from their channel.

**Comment by XataxataX** [comment]
As a workaround, you can use the following. I am having the bot listen for !join and !part messages within its own chat to allow a streamer to request the bot join and part their channel from there. Obviously it needs some proper error checking before joining and parting, but this was just a quick and dirty way to get something functional.

```python
if message.content.lower() == "!join":
        await self.join_channels([message.author.name])
elif message.content.lower() == "!part":
        await self._connection.send(f"PART #{message.author.name}\r\n")
#end if
```

**Comment by EvieePy** [comment]
Give me a day and I'll have something done. The reason this was put on the backburner was because it requires editing the cache, which unfortunately in its current state is quite poorly written.

I'm going to tag this is a 3.0 issue as well as it will need to be implemented there.

Thanks

**Comment by EvieePy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JOIN and PART channel methods and appropriate cache handling.](https://trello.com/c/ZP6utftf/9-join-and-part-channel-methods-and-appropriate-cache-handling)

**Comment by DustGalaxy** [comment]
How to leave a channel in twitchio v3.0.1? I use AutoBot
