### ISSUE TITLE
How to send command of twitch?

### ISSUE THREAD

**Issue by www16852** [TwitchIO/TwitchIO#234]
I want to use a robot to send twitch commands. ex: /timeout user time、 /clear
`
await ctx.send("/clear")
`
But one value is not sent successfully.
Is there a way to solve this problem?

**Comment by chillymosh** [comment]
I recommend you join the discord to ask these questions as it is not an issue with the lib.
https://discord.gg/RAKc3HF

I have posted examples of this before in there.

**Comment by www16852** [comment]
Thank you
Last time I went in I thought there were only python related discussions
