### ISSUE TITLE
Support aiohttp 3.8

### ISSUE THREAD

**Issue by good-live** [TwitchIO/TwitchIO#241]
Is there a specific reason why you require an aiohttp version lower than version 3.8?

**Comment by chillymosh** [comment]
3.8 was in beta up until   31-10-2021 so it's only just been released officially.

**Comment by good-live** [comment]
Sorry if this is the wrong place. Im not on the discord.
But version 3.8 is actively excluded so my question was if there is a reason for that: https://github.com/TwitchIO/TwitchIO/blob/master/requirements.txt

**Comment by IAmTomahawkx** [comment]
We had no reason to support 3.8, so it was not supported. We will see about potentially bumping the dep in a future release.
