### ISSUE TITLE
Include total subscribers when fetch_followers is called

### ISSUE THREAD

**Issue by tkdrob** [TwitchIO/TwitchIO#255]
Including the total subscriber count when calling `fetch_followers` with `to_id` included would be a nice thing to include in the model response.

**Comment by IAmTomahawkx** [comment]
This doesn't work with the way our internal pagination system handles

**Comment by tkdrob** [comment]
In the `request` method in `http.py`, could we have an option to pass the `full_body` argument when calling `fetch_followers` so the full response can be gotten untouched?

**Comment by chillymosh** [comment]
Adjusting the model like this would mean breaking changes
