### ISSUE TITLE
[BUG] - Pubsub (Channelterms)

### ISSUE THREAD

**Issue by Dschogo** [TwitchIO/TwitchIO#259]
Adding and removing permitted or blocked terms throws this error:
![image](https://user-images.githubusercontent.com/36862419/149644570-ba88b152-f4d2-4a3b-a70f-ead4069042ed.png)

Thrown in pubsub ofc.

I think its because not every event got the expires at attribute / expires at field is empty (only those "made" by aotomod when rejecting or allowing terms i think)

Latest TIO 2.1.4

**Comment by IAmTomahawkx** [comment]
1.x isn't supported, did you by chance mean 2.x?

**Comment by Dschogo** [comment]
yeah, 2.1.4 Sorry for the confusion.
