### ISSUE TITLE
content not included on Message documentation.

### ISSUE THREAD

**Issue by ssmele** [TwitchIO/TwitchIO#268]
If you view the Message documentation seen here: https://twitchio.readthedocs.io/en/latest/reference.html#message their is no reference to the content instance variable. Is this intended? Definition of content on Message data class: https://github.com/TwitchIO/TwitchIO/blob/master/twitchio/message.py

**Comment by ssmele** [comment]
It seem's like content is defined differently than the other instance variables on the message class. If this is not intended let me know and I can draft up a MR.

**Comment by EvieePy** [comment]
The Message class seem to be missing class level documentation which is why content would be missing.

**Comment by EvieePy** [comment]
This is not intended so feel free to PR or let me know and I willf fix it

**Comment by ssmele** [comment]
Cool ill give it a try let me get a PR set up.

**Comment by ssmele** [comment]
@EvieePy I have a new branch but I don't have permission to push it up. Can you grant me permission?

**Comment by EvieePy** [comment]
Make a PR

**Comment by ssmele** [comment]
Should this be to master, or development?

**Comment by EvieePy** [comment]
Master

**Comment by IAmTomahawkx** [comment]
fixed in fb49efe
