### ISSUE TITLE
Sending a message to a channel

### ISSUE THREAD

**Issue by 12932** [TwitchIO/TwitchIO#279]
How can I sent a message to a channel? The documentation isn't very helpful, neither is the quick-start.. Surely this is something most bots would need?

**Comment by EvieePy** [comment]
I mean the docs clearly state how to...
https://twitchio.readthedocs.io/en/latest/reference.html#twitchio.Channel.send

**Comment by 12932** [comment]
Thanks, I was looking in the client reference. I didn't think send would be tightly coupled with a `Channel`

**Comment by EvieePy** [comment]
Np. Feel free to join the discord found on the repo readme for further help or open a new issue.
