### ISSUE TITLE
event_ready bug?

### ISSUE THREAD

**Issue by YI3N** [TwitchIO/TwitchIO#284]
For some reason event_ready do not work on 2.2.0, everything is working fine on 2.1.5

**Comment by chillymosh** [comment]
@YI3N are you using capital letters in your inital_channels list? This is a bug that has been fixed if you install direct from git (master). Otherwise change the names in the list to lowercase for now until next release.
You'll be able to get further support by joining the discord.

**Comment by YI3N** [comment]
@chillymosh I have no capital letters in my initial_channels list

**Comment by chillymosh** [comment]
Please try uninstalling and installing direct from git

**Comment by fearfulspoon** [comment]
Same issue, I think. Here is the issue. 

`Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at C:\Users\...\venv\lib\site-packages\twitchio\client.py:173> exception=KeyError('login')>
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\twitchio\client.py", line 178, in connect
    await self._connection._connect()
  File "C:\Users\...\venv\lib\site-packages\twitchio\websocket.py", line 129, in _connect
    self.nick = data["login"]
KeyError: 'login'`

From what I can tell, the API endpoint validating the oauth token is not sending back all of the same data that is listed in the documentation. specifically, seems to be lacking "login" and "user_id" for me. 

Sample return from the validation of my token.
`{'client_id': '...', 'scopes': ['chat:edit', 'chat:read'], 'expires_in': 5452915}`

**Comment by IAmTomahawkx** [comment]
> Same issue, I think. Here is the issue.
> 
> `Task exception was never retrieved future: <Task finished coro=<Client.connect() done, defined at C:\Users\...\venv\lib\site-packages\twitchio\client.py:173> exception=KeyError('login')> Traceback (most recent call last): File "C:\Users\...\venv\lib\site-packages\twitchio\client.py", line 178, in connect await self._connection._connect() File "C:\Users\...\venv\lib\site-packages\twitchio\websocket.py", line 129, in _connect self.nick = data["login"] KeyError: 'login'`
> 
> From what I can tell, the API endpoint validating the oauth token is not sending back all of the same data that is listed in the documentation. specifically, seems to be lacking "login" and "user_id" for me.
> 
> Sample return from the validation of my token. `{'client_id': '...', 'scopes': ['chat:edit', 'chat:read'], 'expires_in': 5452915}`

This was fixed in ccea9ed0a06ffcdfa96d9729d0d34297db318872

**Comment by IAmTomahawkx** [comment]
Your issue doesn't appear to be the same, maybe consider moving to a [Discussion](https://github.com/TwitchIO/TwitchIO/discussions)

**Comment by chillymosh** [comment]
@fearfulspoon your issue is you are using the wrong type of token.
Please join the discord for more help as we don't want to hijack this issue.

**Comment by YI3N** [comment]
@chillymosh sure, I will try it when I have a spare time

**Comment by YI3N** [comment]
The problem was in symbol '#'. Event_ready wont work with initial_channels=['#channel'], but will work with initial_channels=['channel']

**Comment by chillymosh** [comment]
You aren't supposed to use # for the channel list, it isn't in any of the examples

**Comment by YI3N** [comment]
Maybe, but this is not something that I would have done randomly, moreover this worked fine until 2.2.0.

**Comment by chillymosh** [comment]
@YI3N try installing from git, I just pushed a change that should make it work again.
