### ISSUE TITLE
Eventsub fails error code 400

### ISSUE THREAD

**Issue by mtomt** [TwitchIO/TwitchIO#287]
Hello
Im trying to use eventsub but only get Failed to fulfil request (400).
I followed the guide in the docs and set up an https proxy in nginx.
I created an app in dev.twitch.tv and used that credentials in client_id and client_secret
The error comes on the line: "await esclient.subscribe_channel_follows("mikaeltomt")"

Am i doing something wrong or is it a bug in TwitchIO?

**Comment by IAmTomahawkx** [comment]
Hi, this is not an issue with twitchio. As mentioned by the bot, please ask for support in the discord server.
Thanks
