### ISSUE TITLE
Websocket connection was closed: None

### ISSUE THREAD

**Issue by jhagin002** [TwitchIO/TwitchIO#289]
If I disconnect my ethernet, it returns the "Websocket connection was closed: None" error once and then does the "Websocket connection failure" error where it attempts to reconnect with the exponential backoff. After reconnecting my ethernet, it then just gives me the "Websocket connection was closed: None" error and never reconnects to the twitch server. I am not even sure how to break the program if I encounter this error.

**Comment by chillymosh** [comment]
It will eventually reconnect to the websocket. Usually it takes 1-3 minutes but can take up to 15 minutes depending on your connection / OS etc.
But why are you pulling out your ethernet cable? Are you planning on doing this for some reason? Bots are designed to run on stable infrastructure that are designed to minimise all disconnections / downtime e.g. VPS.

If you are simply running this in a local terminal then you can simply ctrl+c to kill it, or `ps -ef` to find the PID and kill it.
I recommend you join the Discord server if you have further questions.

**Comment by jhagin002** [comment]
Oh okay, I was just testing to see what would happen if I were to lose internet. Thank you!

**Comment by chillymosh** [comment]
Potentially improved with ffa83462f76194ef09867dcbec2e31bb552e7e98
