### ISSUE TITLE
Message whitespace is not preserved

### ISSUE THREAD

**Issue by derek-yeetr** [TwitchIO/TwitchIO#293]
Hello,

Early on in the development of my chat bot, I came across an inconvenience where, in order to preserve the arbitrary whitespace of my users' messages, I could not rely on a `Message` object's `content` attribute and had to parse the raw Twitch data manually.

After some digging, I found where the function `parse()` on line 51 of `./parse.py` splits the raw data without a separator: `groups = data.split()`. For a PRIVMSG, the function then uses `message = " ".join(groups[4:]).lstrip(":")` to rejoin the message with single spaces, effectively discarding possibly intentional sequences of redundant whitespace.

By modifying line 51 to separate by a single space with `groups = data.split(" ")`, `Message` contents now represent a PRIVMSG's original whitespace accurately.

Here is some code to demonstrate:
```py
import configparser
import twitchio

CONFIG = configparser.ConfigParser()
CONFIG.read('bot.conf')
CLIENT_ID = CONFIG['CREDENTIALS']['client_id']
TOKEN = CONFIG['CREDENTIALS']['access_token']

client = twitchio.Client(token=TOKEN,
                         client_secret=CLIENT_ID,
                         initial_channels=["derek_yeetr"])
parse = twitchio.parse.parser

@client.event()
async def event_ready():
    print("Connected")

@client.event()
async def event_message(msg):
    if not msg.echo:
        print("Raw data:")
        print(msg.raw_data)
        print("Parsed message content:")
        print(msg.content)

client.run()
```
When the message `A message  with   weird    whitespace.` is sent in my channel, the output without the `split(" ")` change is:
```
Connected
Raw data:
@badge-info=;badges=broadcaster/1;client-nonce=570c27880f93756f640e4ed17387af06;color=#00AABB;display-name=derek_YEETr;emotes=;first-msg=0;flags=;id=49a8c0c7-e091-47ce-9464-c182effbab22;mod=0;room-id=436164774;subscriber=0;tmi-sent-ts=1651124432289;turbo=0;user-id=436164774;user-type= :derek_yeetr!derek_yeetr@derek_yeetr.tmi.twitch.tv PRIVMSG #derek_yeetr :A message  with   weird    whitespace.
Parsed message content:
A message with weird whitespace.
```
And with the change:
```
Connected
Raw data:
@badge-info=;badges=broadcaster/1;client-nonce=bee7ee150ad012915b2672e93396aa24;color=#00AABB;display-name=derek_YEETr;emotes=;first-msg=0;flags=;id=3a73d481-2157-47ac-bfcf-e28e9958af22;mod=0;room-id=436164774;subscriber=0;tmi-sent-ts=1651127127178;turbo=0;user-id=436164774;user-type= :derek_yeetr!derek_yeetr@derek_yeetr.tmi.twitch.tv PRIVMSG #derek_yeetr :A message  with   weird    whitespace.
Parsed message content:
A message  with   weird    whitespace.
```

Since the message body comes at the very end of PRIVMSG data, and I believe there is no chance of consecutive spaces presenting anywhere before it, I see no harm in implementing this three-character change to the source code. If it poses issues for events other than PRIVMSG and WHISPER, perhaps `groups` can be redefined under the respective if-statements to make the proper exceptions.

Thank you for your consideration!

**Comment by IAmTomahawkx** [comment]
We can confirm that this is fixed in 3.0 development. However we view this change as a breaking change due to people expecting the lib to handle whitespace, and as such cannot merge this into 2.x. 

Thanks for the report though
