### ISSUE TITLE
Unknown Author

### ISSUE THREAD

**Issue by heathmanms** [TwitchIO/TwitchIO#298]
I'm confused on if the bot isn't fully authenticating. I create the bot's user token, I login with the oauth screen (I notice there is a warning next to send messages to channels but not next to read) but when the bot replies to people though my username shows up... it only works within my channel. It doesn't work in anyone else's channel and I notice the bot logs the message as an unknown author.

[slivvo][Date: 2022-05-08 21:50:06.404000][User: slivvo][Points: 5]: !points
2022-05-08 21:50:06.093000 - [Unknown Author] -  Hey @slivvo! You have 5 points.

I followed the example given in the documentation, only having added some things. It happens whether I create the user auth token via the token generator or through pyTwitchAPI.

**Comment by chillymosh** [comment]
You need to create a dedicated Twitch account for the bot and use that token.
Do not use your personal account for it.
