### ISSUE TITLE
modify_webhook_subscription fails on subscription verification

### ISSUE THREAD

**Issue by euqimor** [TwitchIO/TwitchIO#30]
**Describe the bug**
When using bot.modify_webhook_subscription(), it fails with the following exception:  
```python
[...]
File "G:\Py\virtualenv\twitch_py37\lib\site-packages\twitchio\http.py", line 109, in _request
    if 'application/json' in resp.headers.get('content-type'):
TypeError: argument of type 'NoneType' is not iterable
```
It seems to be caused by the subscription verification request (see "Subscription Verify Request" [here](https://dev.twitch.tv/docs/api/webhooks-reference/#example-of-webhook-flow)) since it doesn't have a `content-type` field.
Modifying line 109 in `twitchio\http.py` from
```python
if 'application/json' in resp.headers.get('content-type'):
```
to
```python
if resp.headers.get('content-type') and 'application/json' in resp.headers.get('content-type'):
```
solves the issue

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Version: 0.0.3a206+ae55763

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the bot
1. Try using bot.modify_webhook_subscription()

**Expected behaviour**
The subscription is modified with no exceptions thrown :)

**Screenshots**
Not applicable

**(please complete the following information):**
 - OS: Windows 10

**Comment by Senpos** [comment]
Actually, the response contains content type. It is available not in `content-type` header, but in `Content-Type`. I am not sure if it is the same.

By the way, what is the point of checking  headers manually?
**aiohttp** has [content_type property](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=content_type#aiohttp.ClientResponse.content_type) and this check works as intended:
```python
if resp.content_type == "application/json":
    ...
```
