### ISSUE TITLE
:) Parser eats all initial ":" characters in message text

### ISSUE THREAD

**Issue by kamalmostafa** [TwitchIO/TwitchIO#310]
Inappropriate use of lstrip(":") in parse.py parser() munges any messages which actually do begin with ":" character(s) -- they're stripped off too.

Example input message text
``` 
:)
``` 
Yields output message text
``` 
)
``` 
 
Note also that *every* lstrip() call in parse.py is likewise inappropriate.  They're all trying to remove "exactly one of a character", which is not what lstrip() does.  Those other instances of lstrip() maybe won't manifest given normal protocol traffic.  Maybe.

**Comment by chillymosh** [comment]
@kamalmostafa This PR has broken whisper parsing which will need to be addressed.

**Comment by kamalmostafa** [comment]
Thank you for the follow-up fix @chillymosh (oops, sorry for the breakage)!

This looks like its probably okay... But the lstrip() is overzealous and would mis-parse channel names that actually do start with a '#', same as the original problem with stripping too many ':' characters.   (That might not currently occur for Twitch IRC, but it's not unusual in "regular" IRC.)

```
-        channel = result.group("channel")
+        channel = result.group("channel").lstrip("#")
```

The goal is really to chop off exactly one '#' character, so how about this instead?:

```
+        channel = result.group("channel")[1:]
```

Thanks again, and also for TwitchIO :smiley:

**Comment by chillymosh** [comment]
`channel = result.group("channel")[1:]` would most likely work but channel names are usernames which are not allowed to contain any symbols other than an underscore, so starting with a `#` is not possible.
Twitch uses a customised version of IRC v3 so bringing up "regular" IRC is not relevant as we will never connect to anything outside of Twitch.
