### ISSUE TITLE
A weird _process_data error in console

### ISSUE THREAD

**Issue by Commaster** [TwitchIO/TwitchIO#314]
```
Traceback (most recent call last):
  File ".../python3.8/site-packages/twitchio/websocket.py", line 308, in _process_data            
    await partial_(parsed)                                 
  File ".../python3.8/site-packages/twitchio/websocket.py", line 427, in _usernotice              
    tags = dict(x.split("=") for x in rawData.split(";"))  
ValueError: dictionary update sequence element #21 has length 3; 2 is required
```

I have no clue how or why this happened 🤔

**Comment by chillymosh** [comment]
The cause of this is possibly due to an = in the message content of a subscription message or other USERNOTICE message.

**Comment by chillymosh** [comment]
It will continue running

**Comment by Commaster** [comment]
Maybe x.split("=", **maxsplit=1**) will solve this? 🤔

**Comment by chillymosh** [comment]
We were waiting for the merge of the and refactoring of the IRC parser before addressing this. We will look further into it soon.

**Comment by chillymosh** [comment]
@Commaster `tags = dict(x.split("=", 1) for x in rawData.split(";"))` will most likely work if you would like to test locally on 2.4.0 

install direct from git
```
python -m pip install -U --force-reinstall git+https://github.com/TwitchIO/TwitchIO.git
```

**Comment by Commaster** [comment]
Oh! I was wondering why 2.4.0 wasn't showing up in pypi. Thank you, I shall try! (Though I haven't seen this exact error in quite some time, mostly just #209)

**Comment by chillymosh** [comment]
@Commaster 2.4.0 is now available on pypi. We have updated the join_channels logic in this version, although not sure how #209 is relevant to this issue?

**Comment by chillymosh** [comment]
Revisiting this since I am going to be updating some websocket / parser things soon, I believe the user-type also needs to be amended here
```
tags = dict(x.split("=", 1) for x in d.split(";"))
tags["user-type"] = tags["user-type"].split(":tmi.twitch.tv")[0].strip()
```

**Comment by chillymosh** [comment]
@Commaster pushed to Master
