### ISSUE TITLE
Helix API `fetch_channel` could request 100 broadcasts at once

### ISSUE THREAD

**Issue by ccppoo** [TwitchIO/TwitchIO#317]
Current `class Client::fetch_channel` method only allows single channel information API request

https://github.com/TwitchIO/TwitchIO/blob/d7512f6797e9f8b46e8a36050b53d2f62a6d1223/twitchio/client.py#L443-L471

![image](https://user-images.githubusercontent.com/46418312/183097446-216dbe54-b4b4-4d49-97c4-93fa963941fc.png)

[Twitch API ref Link](https://dev.twitch.tv/docs/api/reference#get-channel-information)

before making PR, should it be fetch_channel or fetch_channel**s** ?

or make it deprecated for next version with warning?

```python
async def fetch_channels(self, broadcaster: Union[str, List[str]] ):
       # ...

async def fetch_channel(self, broadcaster: Union[str, List[str]] ):
        # ...

        logging.info("Deprecated use 'fetch_channels' instead of 'fetch_channel' ")
        return await self.fetch_channels( ... ) 
```

**Comment by chillymosh** [comment]
I already have something prepared for this before next release 2.x release, that I haven't pushed yet.
fetch_channel will be fully removed in 3.0.

**Comment by chillymosh** [comment]
I've just pushed the changes if you would like to try

**Comment by ccppoo** [comment]
> I've just pushed the changes if you would like to try

works well
