### ISSUE TITLE
choose specific time to sleep when using decorator `routines.routine`

### ISSUE THREAD

**Issue by ccppoo** [TwitchIO/TwitchIO#323]
Current explanation about `wait_first` in doc is ambiguous.

https://github.com/TwitchIO/TwitchIO/blob/14b0880d9c22f6fc599f23ddbcb08e1aa8c962c4/twitchio/ext/routines/__init__.py#L364-L366

It says it waits for **specific time** so, this could be understood as it's requiring `int` or `float`.

https://github.com/TwitchIO/TwitchIO/blob/14b0880d9c22f6fc599f23ddbcb08e1aa8c962c4/twitchio/ext/routines/__init__.py#L390-L407

But it actually waits for time to  wait before the next iteration of the routine. ↑

https://github.com/TwitchIO/TwitchIO/blob/14b0880d9c22f6fc599f23ddbcb08e1aa8c962c4/twitchio/ext/routines/__init__.py#L288-L289

`delta` passed to `Routine` is used wait for next iteration as the code shows ↑

---

## proposal 

add `wait_for` keyword parameter requiring `int` or `float` to wait for **specific time**

```python
@routines.routine(seconds=600,wait_for=20)
async def do_this_job_every_20_sec(self):
    await do_something( ... )
    ...
```

for example `wait_for` key word will be used for jobs that has `time out` like DB connections

that should run first in the place when the app started **and  then** run after every 10 minutes

**Comment by chillymosh** [comment]
The type hint shows if it takes a value it has to be a bool so it is not ambiguous as to whether it could be an int or a float.
The argument name of `wait_first` implies the question "Would you like to wait first before the first iteration", where specified time is the routine loop interval.
The docs can be updated to reflect this better.

**Comment by ccppoo** [comment]
@chillymosh  I haven't thought using `@before.routine`  thanks ,my bad

**Comment by ccppoo** [comment]
Just for someone else like me
![Untitled Diagram drawio(2)](https://user-images.githubusercontent.com/46418312/185799387-0fe93f16-c880-4d2a-8f5b-e2fd544b9f43.png)

**Comment by chillymosh** [comment]
Closing as not an issue.
