### ISSUE TITLE
models.py Stream :: game_id, game_name attribute could be empty string

### ISSUE THREAD

**Issue by ccppoo** [TwitchIO/TwitchIO#328]
![image](https://user-images.githubusercontent.com/46418312/187080171-e13a1ac1-d229-4f52-99ed-3732b712b840.png)

There are cases where streamer didn't set their game_name while streaming.

Unlike Twitch System automatically generates `Tags` after few seconds like I mentioned at https://github.com/TwitchIO/TwitchIO/issues/324 ,

`game_id`, `game_name` weren't generated until the streamer changes it.

There was no explanations in case of `game_id` and `game_name` sent as empty string in Twitch API Doc.

and couldn't find other cases like this in blogs, stackoverflow questions.

**Comment by chillymosh** [comment]
Twitch does indeed send these as empty strings rather than None or null type and the models reflect this, as per their documentation.
```
'game_id': '', 'game_name': '', 'type': 'live',
```
Whether we can change the model to make these Optional or not and return None by simply adding `or None` to the model will need to be discussed, or left as a change for 3.0

**Comment by ccppoo** [comment]
@chillymosh 
yes, it will be better using `@property` decorators saving origin values(str) and then handling, 

such as type casting string to int or empty string to `None` could be more useful for future maintenance 

so does issue https://github.com/TwitchIO/TwitchIO/issues/325 and https://github.com/TwitchIO/TwitchIO/issues/324

**Comment by IAmTomahawkx** [comment]
We will not be changing this, as it is true to the API, and changes made to turn this to None or whatever constitute a breaking change.

**Comment by ccppoo** [comment]
Not in the docs, nor TwitchIO Doc
somebody just getting a exception not knowing what just happend in runtime
and you are saying API is working fine all time
