### ISSUE TITLE
Bot object has no attribute

### ISSUE THREAD

**Issue by c20xh2** [TwitchIO/TwitchIO#33]
**Describe the bug**
Running the example script, bots connect to the chat but send :

```
python3 main,py
Ready | lightshow
ThIS IS A TEST
Task exception was never retrieved
future: <Task finished coro=<Bot.event_message() done, defined at main.py:14> exception=AttributeError("'Bot' object has no attribute 'process_commands'",)>
Traceback (most recent call last):
  File "main.py", line 16, in event_message
    await self.process_commands(message)
AttributeError: 'Bot' object has no attribute 'process_commands'
````
**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
```pip show twitchio
Metadata-Version: 1.1
Name: twitchio
Version: 0.0.3a210+50eb5ae
Summary: A python IRC and API wrapper for Twitch.
Home-page: https://github.com/EvieePy/TwitchIO
````

**To Reproduce**
Steps to reproduce the behaviour:
Run the example script

**(please complete the following information):**
 - OS: [Ubuntu 16.04.5 LTS]

**Additional context**

**Comment by c20xh2** [comment]
Forget it, definitly something wrong with my python install

**Comment by c20xh2** [comment]
After double checking everything it seems the issue with the example code is real

**Comment by Adure** [comment]
its now `Bot.handle_commands()` the example code must still be outdated
