### ISSUE TITLE
TwitchIO sounds extension doesn't recognize ffmpeg on Linux

### ISSUE THREAD

**Issue by NordsofMorrow** [TwitchIO/TwitchIO#334]
I've been trying to get things working for sounds on Linux, but have not been successful. Despite there being a check for `ffmpeg` being installed (https://github.com/TwitchIO/TwitchIO/blob/a9e157bad5eac1e7148e6d76f291fd2e4c19a047/twitchio/ext/sounds/__init__.py#L48), on import this fails to recognize it. 

When hardcding this value to `True` then attempts to launch `ffmpeg.exe` (https://github.com/TwitchIO/TwitchIO/blob/a9e157bad5eac1e7148e6d76f291fd2e4c19a047/twitchio/ext/sounds/__init__.py#L142), so I imagine this extension is only Windows-supported at the moment. Would it be possible to make a mention in the docs that this is the case? (Changing this value to `ffmpeg` raises a bunch of alsalib issues, so I imagine there are still more than a few outstanding issues that are beyond the scope of TwitchIO, which is fine).

**Comment by natir** [comment]
@NordsofMorrow I already write a pull request to try to solve this issue. #327

**Comment by chillymosh** [comment]
This should be solved in the merged PR #327
