### ISSUE TITLE
Add "created_at" and "ended_at" parameters when fetching Twitch clips

### ISSUE THREAD

**Issue by graille** [TwitchIO/TwitchIO#353]
[Twitch endpoint to get clips](https://dev.twitch.tv/docs/api/reference#get-clips) allows the usage of "started_at" and "ended_at" parameters to avoid server and network overload when you only needs clips generated at a specific date.

The [TwitchIO method](https://twitchio.dev/en/latest/reference.html#twitchio.PartialUser.fetch_clips) doesn't implement this. So we always have to transfer all the clips of the channel (1500+ in my case) and then, sort them by date afterwards.

Would be nice to add two new parameters to the function.

**Comment by chillymosh** [comment]
I believe you meant to link the PartialUser.fetch_clips method?

**Comment by graille** [comment]
> I believe you meant to link the PartialUser.fetch_clips method?

Yep sorry, I edited my first message
