### ISSUE TITLE
Add the new Get-Chatters endpoint

### ISSUE THREAD

**Issue by graille** [TwitchIO/TwitchIO#354]
Twitch API [just released a new endpoint](https://dev.twitch.tv/docs/api/reference#get-chatters) to obtain a list of users watching the stream

It would be nice to add a PartialUser.fetch_chatters(moderator_id, token) methods to cover this endpoint
Regarding the arguments, I propose the following :
- An optional argument **moderator_id**, if not specified, the user performing the request would be the current PartialUser user
- An optional **token** argument to provide a token matching the moderator_id

**Comment by IAmTomahawkx** [comment]
We do not add beta endpoint to the library, sorry. It will be added once it comes out of beta
