### ISSUE TITLE
Get Streams API Bug

### ISSUE THREAD

**Issue by sabal202** [TwitchIO/TwitchIO#365]
# Issues

Background: I wanted to get top live streams by chosen languages.

Issues I encountered:

1. In TwitchHTTP class function `get_streams` does not provide `type` parameter ([link](https://github.com/TwitchIO/TwitchIO/blob/master/twitchio/http.py#L675)).

    As said in [twitch dev reference](https://dev.twitch.tv/docs/api/reference#get-streams) Get streams have parameter `type`:
    
    ```
    The type of stream to filter the list of streams by. Possible values are: all, live.
    The default is all.
    ```

2. In Client `fetch_streams` function  also does not have `type` parameter, but also introduce `assert user_ids or game_ids or user_logins` ([link](https://github.com/TwitchIO/TwitchIO/blob/master/twitchio/client.py#L676)). This assert prohibits use of only languages parameter and none of parameters while twitch API allows that behavior.

# Possible solution

1. Add `type: Optional[Literal["all", "live"]] = None` to both `Client.fetch_streams` and `TwitchHTTP.get_streams` as argument.
2. Remove assert from `Client.fetch_streams`.

**Comment by IAmTomahawkx** [comment]
fixed!
