### ISSUE TITLE
hi ı need little more info

### ISSUE THREAD

**Issue by kubilayyalcinyt** [TwitchIO/TwitchIO#369]
how ı give bot name and python input is possible ? ı try prank my friend he think ı create real ai thanks
pysimplegui or tkinter is possible ?

**Comment by chillymosh** [comment]
Please open a Discussion topic or join the discord for support questions as this is not an issue with the lib.

But you can't change the bot name, it's linked to the token of the account you setup for the bot.
Using a GUI with an async framework like this is not straight forward.
