### ISSUE TITLE
Client :: etch_stream search option "language" is not counted as option 

### ISSUE THREAD

**Issue by ccppoo** [TwitchIO/TwitchIO#374]
from `Client` class method `fetch_streams` 

at the line preventing empty query options there are `assert` (Line 676)

https://github.com/TwitchIO/TwitchIO/blob/bd73cc53751282eeaac16c83f3cce207a5bc5763/twitchio/client.py#L674-L685

From docs, fetch_stream [query options are optional](https://dev.twitch.tv/docs/api/reference#get-streams)

should be changed to 

```py
assert user_ids or game_ids or user_logins or languages
```

So people could use `fetch_streams` searching for specific language stream

---

example: 

```py
class Bot(Client):
    # ...

    async def event_ready(self):
        await self.fetch_streams(languages=["ko", "jp"])
```

this throws me an `AssertionError`

**Comment by chillymosh** [comment]
This has already been raised in https://github.com/TwitchIO/TwitchIO/issues/365

**Comment by IAmTomahawkx** [comment]
Tracked in #365
