### ISSUE TITLE
I can't use twitch commands in chat as moderator with twitchio.

### ISSUE THREAD

**Issue by Xxrob22xX** [TwitchIO/TwitchIO#384]
`ctx.channel.send(f"/delete {ctx.id}")` it doesn't work anymore, and it doesn't work with /timeout or /clear either. the bot uses my account (with full moderator permissions) but can't use any twitch commands, but I can use them. It used to work, but now it doesn't work anymore. the bot is still able to read and write in the chat.

I don't know if it's an external problem or mine.

**Comment by chillymosh** [comment]
@Xxrob22xX Twitch deprecated/commands for bots. You now have to use the Helix endpoints to carry out these tasks.

**Comment by Gouvernathor** [comment]
What does that mean ? What is the class and method to send these Helix endpoints ?

**Comment by EvieePy** [comment]
Regarding your issue https://github.com/TwitchIO/TwitchIO/issues/388#issuecomment-1556049097

Most chat commands are associated with the User and bot can no longer send commands via IRC/Chat.

https://twitchio.dev/en/latest/reference.html#twitchio.PartialUser.chat_announcement

**Comment by Gouvernathor** [comment]
Thanks for the info ! it's a bit weird that the token and user id must be given explicitly since we only have one of each anyway (and .send doesn't require that for example). But that's for another issue.

**Comment by IAmTomahawkx** [comment]
This is not usually true. Any bot that scales beyond one streamer will have multiple tokens and user ids, and as such they need to be specified somewhere. Send does not require tokens because it doesn't make API calls. It uses the IRC connection that is already authenticated
