### ISSUE TITLE
Issue with RECONNECT in PubSub

### ISSUE THREAD

**Issue by klyasht** [TwitchIO/TwitchIO#385]
Got in my project log:
`2023-02-24 18:59:03 [T:MainThread] DEBUG:twitchio.ext.pubsub.websocket: Pubsub event referencing unknown event 'RECONNECT'. Discarding`

It's expected (according to the current Twitch [docs](https://dev.twitch.tv/docs/pubsub/#connection-management)) that RECONNECT has own type in received message. The straightforward solution would be move [this](https://github.com/TwitchIO/TwitchIO/blob/master/twitchio/ext/pubsub/websocket.py#L202) to method `handle_reconnect`.

**Comment by chillymosh** [comment]
Thanks, we are aware of this already and is currently in testing before we commit.
