### ISSUE TITLE
Missing attribute at 'class twitchio.Chatter'

### ISSUE THREAD

**Issue by robezonetv** [TwitchIO/TwitchIO#391]
Hi,

We foundout that we can get author.name and non-documented value (user_id ~ twitch_id) as in author.id (but this value is not documented.

Is possible to fix it? I can't find how to make pull request in doc for this update.

Thank you in advance.

**Comment by chillymosh** [comment]
@robezonetv please install from Master as Chatter.id has now been added publicly
