### ISSUE TITLE
Replace cchardet dependency with faust-cchardet

### ISSUE THREAD

**Issue by iarspider** [TwitchIO/TwitchIO#393]
CChardet fails to build for Python 3.11 on Windows [link](https://github.com/PyYoshi/cChardet/issues/81), and the developer is nowhere to be found. There is a forked fixed version `faust-cchardet` (see [this](https://github.com/PyYoshi/cChardet/issues/81#issuecomment-1329693378) comment) that can be used instead.

**Comment by iarspider** [comment]
Installation of cchardet fails for me with Python 3.11.3 (Windows 10 x64, version from MS Store)

**Comment by EvieePy** [comment]
Hey thanks for bringing up this issue.

We are probably going to make a custom pip index so that these dependencies are available now and for future versions of Python.

I'll update you once we have a working index.

**Comment by EvieePy** [comment]
Hello, please see #394 for a fix and thanks for bringing this up.

**Comment by IAmTomahawkx** [comment]
resolved through the index at https://pip.twitchio.dev/ . Please see the installing page on the master branch for more details.
