### ISSUE TITLE
Issue with whispering users

### ISSUE THREAD

**Issue by mja00** [TwitchIO/TwitchIO#55]
When I try to whisper a user use ctx.author.send("message") it tells me that the dataclass User has no attribute send. Is there a different way of doing this?

**Comment by EvieePy** [comment]
As of 2.0 this should be fixed. Unfortunately 2.0 is not ready for production, but I will be sure to let you know when it is.

Sorry for the late reply.

**Comment by IAmTomahawkx** [comment]
I'm aware this is an old issue, but 2.0, while not the most stable, can be used now
