### ISSUE TITLE
Message._timestamp not set on commands that exist

### ISSUE THREAD

**Issue by bsquidwrd** [TwitchIO/TwitchIO#56]
**Describe the bug**
When running a command that exists, it seems the `Message._timestamp` attribute doesn't exist

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
`0.0.4a295+665c7ce`

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create a bot with cogs/modules
2.  Create a function in the Bot class `event_message`
3.  Put some way to show the timestamp of every message (`print(message.timestamp)`)
4.  Run the bot
5.  Run a command that doesn't exist -> get timestamp
6.  Run a command that does exist -> get error

**Expected behaviour**
Have timestamp set on every message, no matter what.

**Screenshots**
[<img src="https://i.imgur.com/gwp26OB.png" />](https://i.imgur.com/gwp26OB.png)

**(please complete the following information):**
 - OS: Windows 10 64bit

**Additional context**
```
future: <Task finished coro=<Bot.event_message() done, defined at .\bot.py:54> exception=AttributeError('_timestamp')>
Traceback (most recent call last):
  File ".\bot.py", line 57, in event_message
    timestamp = message.timestamp
  File "D:\Personal\Resilio Sync\My Files\twitch_bot\env\lib\site-packages\twitchio\dataclasses.py", line 88, in timestamp
    timestamp = datetime.datetime.utcfromtimestamp(self._timestamp/1000)
AttributeError: _timestamp
```

**Comment by bsquidwrd** [comment]
As of right now, my workaround is to not rely on the timestamp and rather generate my own on `event_message` using the following:

```python
timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
```

**Comment by EvieePy** [comment]
Are you by any chance overriding modes kwarg in bot? This seems to be an issue with not receiving the correct tags from Twitch. They may have possibly changed something, I will look into it for you.

Thanks

**Comment by bsquidwrd** [comment]
Here's the code I'm working with right now: https://github.com/bsquidwrd/Example-TwitchIO-Bot

As far as I know, I'm not overriding modes, and whenever I looked at the `Message.tags` value it has a timestamp in there.

**Comment by EvieePy** [comment]
I have a fix, will push tomorrow thanks for the find!

**Comment by bsquidwrd** [comment]
Glad to hear! Thank you
I'm anxious to see what it was.

With discord.py and this library, I'm trying to learn how to make async libraries like the amazing ones.

**Comment by bsquidwrd** [comment]
Any luck on pushing the fix for this?

**Comment by SnowyLuma** [comment]
Some real life events have come up so @EvieePy hasn't been available, she should be back sometime this week to resume work on TwitchIO and also this issue.

**Comment by EvieePy** [comment]
Should be Fixed as of https://github.com/TwitchIO/TwitchIO/commit/f8956fdef93a371017a630a0c3f36424c8280a24
Thanks for the issue and sorry it took so long. Let me know if you run into more issues.

**Comment by bsquidwrd** [comment]
Awesome, thanks!
