### ISSUE TITLE
Known/Verified Bots Rate Limits

### ISSUE THREAD

**Issue by Marenthyu** [TwitchIO/TwitchIO#61]
In ``cooldowns.py``, the correct Rate Limits for normal users/bots are used. However, as [the docs](https://dev.twitch.tv/docs/irc/guide/#command--message-limits) state, one may be a known or verified bot, giving increased rate limits.

This ought to be reflected in the code; I will open a PR later today if i get the chance.

The information about an account being a known or verified bot can be gotten from kraken / v5 via ``https://api.twitch.tv/kraken/users/<id>/chat``

**Comment by EvieePy** [comment]
I'm happy for you to make a PR, otherwise I will probably just implement this into 2.0.
