### ISSUE TITLE
Websocket Exceptions

### ISSUE THREAD

**Issue by Drethic** [TwitchIO/TwitchIO#80]
**Describe the bug**
After running the example code 3 exceptions appear in the console.  The bot does seem to enter the Twitch room and respond to commands.  The main issue is these errors can mask real issues when expanding past the example.

First is an error with `join_action` in `twitchio/websocket.py:558` stating the task to join never finished.

Second is an error with `_join_channe` stating the task timed out and to check if the channel exists.

Third is an error with `WebSocketCommonProtocol.close` stating `self._websocket.close()` was never awaited.  This happens when I stop the bot with `ctrl+c`

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
1.0.0

**To Reproduce**
Steps to reproduce the behaviour:
Use the following code with a valid irc_token:
[Code Snippet](https://pastebin.com/Xdz5NwZy)

**Expected behaviour**
No exceptions in the console when using the example code.

**Screenshots**
I don't have screenshots, but I do have [logs](https://pastebin.com/DbCXiKRL)

**(please complete the following information):**
 - OS: Mac Majave
- Shell: zsh and bash
- Python 3.7

**Additional context**
N/A

**Comment by adrenaline681** [comment]
I'm getting the same errors, using Windows and Python 3.7.
Did you find a solution to this?

**Comment by Drethic** [comment]
I have not found a solution and have since moved from Twitch to Mixer so probably won't be working with this library any more.
