### ISSUE TITLE
get_users,get_streams,get_stream|Not working as intended/broken

### ISSUE THREAD

**Issue by dusty-dusty** [TwitchIO/TwitchIO#94]
**Describe the bug**
get_users, type is always blank even if the channel is live or not.(Shown in pictures)
get_streams, return is always blank when imputing channel names/ id's (Shown in pictures)
get_stream, returns None when a channel is offline but if its online it freezes/breaks and nothing under the code will be executed(shown in pictures).

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
1.0.0

**To Reproduce**
Steps to reproduce the behaviour:
code is shown in pictures, if you need full code tell me.

**Expected behaviour**
How the wiki explains it.

**Screenshots**

https://i.imgur.com/aJW4kse.png  Online
https://i.imgur.com/Of9ZAbX.png  Offline

**(please complete the following information):**
tried on Windows 10 and linux
tried on Python 3.7.5 and 3.6.2

**Additional context**

Here is a fix I wrote for myself not using twitchio

```
import urllib.request
import urllib.error
import json

def liveCheck( chan_name  ):
    try:
        url = f"https://api.twitch.tv/helix/streams?user_login={chan_name}"
        heading = {
            "Client-ID": "myOauth"
        }
        req = urllib.request.Request( url , headers = heading )
        response = urllib.request.urlopen( req )
        output = json.loads( response.read() )
        output = output["data"]
        for i in output:
            output = i
        if "type" in output:
            return True
        else:
            return False
    except Exception as e:
        print( 'gettwitchapi' , e )
        return e
```

**Comment by EvieePy** [comment]
Try updating the lib with the GitHub version.

**Comment by IAmTomahawkx** [comment]
These have all been fixed with recent-ish updates of twitchio
