### ISSUE TITLE
Case insensitivity for commands

### ISSUE THREAD

**Issue by CaptainWilder** [TwitchIO/TwitchIO#95]
Requesting commands to be case insensitive, or have support for .casefold().

**Comment by ParkEunBlank** [comment]
you can get around this by doing something like this
`    async def event_message(self, message):
        ctx = await bot.get_context(message=message)
        if str(message.content).lower().startswith("!tester"):
            await self.testercommand(ctx)`

**Comment by BairdMcI** [comment]
Bump for TIO v2 :)

**Comment by IAmTomahawkx** [comment]
turns out this is already complete on 2.0, and apparently a duplicate of #78 . I probably shouldve paid closer attention earlier

**Comment by Houdini111** [comment]
I can't find anything in the documentation, nor in any PRs, nor in the code about this. How do you enable case insensitive commands?

**Comment by chillymosh** [comment]
@Houdini111 for questions like these it is best to join the discord support server and ask, or use the Github Discussions
```
class TwitchChatBot(commands.Bot):
    def __init__(self):
        super().__init__(
            token="",
            client_secret=config["CLIENT_SECRET"],
            prefix="!",
            initial_channels=["ch1", "ch2"],
            case_insensitive=True,
        )
```
