### ISSUE TITLE
Issue reciving whispers

### ISSUE THREAD

**Issue by DiVitoTommaso** [TwitchIO/TwitchIO#96]
i tried 
async def event_message(self, message):
        print(message)
        await self.handle_commands(message)

but it doesn't recive whispers 
how should i do to recive/read whispers?
Version: 1.0.0 - windows

**Comment by ParkEunBlank** [comment]
You can use event_raw_data. I dont think they have implemented the whisper things yet. and to send whispers you would have to send it via the websocket
